resources/views/defaultsite/desktop/components-ui/ui-trending-tag.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php
show trending tag for defaultsite
=> fix: trending tag

public/static/assets/css/styles.css, public/static/assets/js/script.js, resources/views/defaultsite/desktop/components-ui/ui-gallery-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-news.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/ui/components/slider-news.blade.php
slider belum rapi 100% karena ukuran CDN server, belum bisa dipahami dengan baik
=> feat:slider

resources/views/defaultsite/desktop/components-ui/ui-breaking-news.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php
fix: dapat mengimplementasikan API ke dalam fitur breaking news
=> fix:mengimplementasikan API ke dalam fitur breaking news

resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php
=> feat: sidebar news

resources/views/defaultsite/desktop/components-ui/ui-promotion.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php
=> add ui-promotion

resources/views/defaultsite/desktop/components-ui/ui-main-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-promotion.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/image.blade.php
change token API, 
config image.blade.php for CDN application
restruktur folder
=> docs: change token, add some config

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-main-news.blade.php
perbaikan image container slider pada komponen slider
=> fix:perbaikan image container pada slider

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-breaking-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-spotlight-news.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php
=> fix: slider css

resources/views/defaultsite/desktop/components-ui/ui-latest-news.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php
=> bug/fix latest-news

resources/views/defaultsite/desktop/components-ui/ui-gallery-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-latest-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-list-main-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-more-info.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-spotlight-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-tab-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-collection.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/tag.blade.php
page : index-tag-paging, belum rapi .. css masih perlu diperbaiki..  @edwindamanik 
url_news gagal call api @lanuma dibagian   <a href="{{ Src::detail($latest[1]) }}" aria-label="{{ $latest[1]['news_title'] ?? null }}">
di page home
=> pages: index-tag-paging

app/Helpers/Data.php, resources/views/defaultsite/desktop/components-ui/ui-credit.blade.php, resources/views/defaultsite/desktop/components-ui/ui-read-too.blade.php, resources/views/defaultsite/desktop/components-ui/ui-share-news.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/readpage.blade.php
=> pages: detail, feat:credits

app/Helpers/Data.php, resources/views/defaultsite/desktop/components-ui/ui-aside.blade.php, resources/views/defaultsite/desktop/components-ui/ui-latest-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/readpage.blade.php
=> fix:bug aside

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-gallery-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-latest-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php
=> fix: styles img

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-gallery-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-more-info.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-collection.blade.php, resources/views/defaultsite/desktop/pages/tag.blade.php
fix component video & photo collection
=> fix: page article & ITP

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-main-content-news.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/readpage.blade.php
menampilkan data dinamis pada form report
=> fix: form report dengan data yang dinamis

app/Helpers/Data.php, app/Http/Controllers/DefaultSite/NewsController.php, public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-footer.blade.php, resources/views/defaultsite/desktop/components-ui/ui-index-kanal.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-more-info.blade.php, resources/views/defaultsite/desktop/components-ui/ui-pagination.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-related-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-search-index.blade.php, resources/views/defaultsite/desktop/components-ui/ui-spotlight-news.blade.php, resources/views/defaultsite/desktop/pages/category.blade.php, resources/views/defaultsite/desktop/pages/readpage.blade.php, resources/views/defaultsite/desktop/pages/tag.blade.php, resources/views/defaultsite/mobile/components-ui/index-kanal.blade.php, resources/views/ui/components/related-news.blade.php
add new feat : related news, refactoring some code on page: tag & fix css
=> Related news

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-form-report.blade.php, resources/views/defaultsite/desktop/components-ui/ui-latestphoto.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/photo_detail.blade.php
fix: tampilan video detail beserta tampilan untuk kumpulan beberapa foto dengan carousel
=> fix:photo-details

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-list-text.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-promotion.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/category.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php
using Intersection Observer API as MDN, just applied on home.blade.php (desktop)
=> feat: lazyLoader

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-credit.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/pages/tag.blade.php, resources/views/defaultsite/desktop/pages/video_detail.blade.php
=> fix: pages tag

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/pages/video_detail.blade.php
fix tag a decoration none to all elements
=> fix : style related-news

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-gallery-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-header.blade.php, resources/views/defaultsite/desktop/components-ui/ui-latest-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-latestphoto.blade.php, resources/views/defaultsite/desktop/components-ui/ui-list-main-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-list-text.blade.php, resources/views/defaultsite/desktop/components-ui/ui-list-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/components-ui/ui-spotlight-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-trending-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-news.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/author.blade.php, resources/views/defaultsite/desktop/pages/category.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/static.blade.php, resources/views/defaultsite/desktop/pages/tag.blade.php, resources/views/defaultsite/desktop/pages/video.blade.php, resources/views/defaultsite/mobile/components-ui/slider.blade.php, resources/views/image.blade.php, routes/web.php
=> feat: page video

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-header.blade.php, resources/views/defaultsite/desktop/pages/category.blade.php, resources/views/defaultsite/desktop/pages/search.blade.php
=> feat: page search

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-list-text.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/components-ui/ui-spotlight-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-trending-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-news.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/search.blade.php, resources/views/defaultsite/desktop/pages/video.blade.php
=> fix:style/video

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/index-berita.blade.php
=> feat: page index-berita

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-list-text.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-news.blade.php, resources/views/defaultsite/desktop/pages/category.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/index-berita.blade.php
fix page tag ux.. Note : UI gallery masih belum fix
=> refactore: fix some styling & ux

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/pages/contact_us.blade.php
dapat menampilkan halaman kontak kami dengan form berupa nama, email, nomor hp, subject, content
=> fix:menampilkan halaman kontak kami

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/index-berita.blade.php, resources/views/defaultsite/desktop/pages/video.blade.php
=> style: fix video page

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-list-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/components-ui/ui-video-collection.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/tag.blade.php
=> refactore : main blade

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-gallery-news.blade.php
memperbaiki grid pada komponen gallery news
=> fix: perbaikan styling pada component gallery news

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-gallery-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/index-berita.blade.php, resources/views/defaultsite/desktop/pages/photo.blade.php
=> fix main-news-container

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-credit.blade.php, resources/views/defaultsite/desktop/components-ui/ui-more-info.blade.php, resources/views/defaultsite/desktop/components-ui/ui-populer-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-share-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-sidebar-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/index-berita.blade.php, resources/views/defaultsite/desktop/pages/video.blade.php
fix styling and refactoring some bad code
=> refactor: clean code

app/Http/Controllers/DefaultSite/NewsController.php, public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-form-report.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-related-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/components-ui/ui-spotlight-news.blade.php, resources/views/defaultsite/desktop/pages/video_detail.blade.php
=> refactor:video detail

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-not-found.blade.php, resources/views/defaultsite/desktop/error/404.blade.php
=> feat: page 404

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-footer.blade.php
fix:memperbaiki social media pada footer
=> fix:memperbaiki social media pada footer

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-main-content-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-pagination.blade.php, resources/views/defaultsite/desktop/components-ui/ui-pagination2.blade.php
=> feat: pagination readpage

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-form-report.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-news.blade.php, resources/views/defaultsite/desktop/components-ui/ui-main-content-video.blade.php, resources/views/defaultsite/desktop/components-ui/ui-photo-collection.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/photo_detail.blade.php, resources/views/defaultsite/desktop/pages/video_detail.blade.php, resources/views/defaultsite/mobile/amp/components-ui/main-news-article.blade.php, resources/views/defaultsite/mobile/amp/components-ui/populer-news.blade.php, resources/views/defaultsite/mobile/amp/components/trendingtag.blade.php, resources/views/defaultsite/mobile/amp/pages/readpage.blade.php, resources/views/defaultsite/mobile/components-ui/form-report.blade.php, resources/views/defaultsite/mobile/layouts/ui-main.blade.php
=> refactor: ganti bahasa ke inggris

lang/id/global.php
ubah name bulan ke bahasa inggris
=> refactor: lang english

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-aside.blade.php, resources/views/defaultsite/desktop/components-ui/ui-footer.blade.php, resources/views/defaultsite/desktop/components-ui/ui-header.blade.php, resources/views/defaultsite/desktop/components-ui/ui-list-video.blade.php, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/category.blade.php, resources/views/defaultsite/desktop/pages/home.blade.php, resources/views/defaultsite/desktop/pages/index-berita.blade.php, resources/views/defaultsite/desktop/pages/video.blade.php
=> feat: ads-wrapper

resources/views/defaultsite/desktop/components-ui/ui-footer.blade.php
=> static page dump

resources/views/defaultsite/desktop/components-ui/ui-not-found.blade.php, resources/views/defaultsite/mobile/components-ui/not-found.blade.php
=> refactor: 404 page

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-share-news.blade.php
=> fix:copy link button

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/pages/photo_detail.blade.php
button read more (caption) di photo detail
=> feat : readmore button

resources/views/defaultsite/desktop/pages/photo_detail.blade.php
=> hapus dump

public/static/assets/css/styles.css, resources/views/defaultsite/desktop/components-ui/ui-slider.blade.php, resources/views/defaultsite/desktop/components-ui/ui-spotlight-news.blade.php
fix performance based on lighthouse
=> fix: performance web

app/Http/Controllers/DefaultSite/NewsController.php, public/static/assets/css/styles.css, resources/views/defaultsite/desktop/layouts/ui-main.blade.php, resources/views/defaultsite/desktop/pages/photo_detail.blade.php
=> redesign : photo detail

resources/views/defaultsite/mobile-v2/layouts/main.blade.php
=> fix main navbar

app/Http/Controllers/DefaultSite/NewsController.php, config/trstdly.php, resources/views/defaultsite/mobile-v2/layouts/main-maverick.blade.php
=> meta-data tag & detail

app/Helpers/Data.php, app/Http/Controllers/DefaultSite/CategoryController.php, app/Http/Controllers/DefaultSite/IndexBeritaController.php, app/Http/Controllers/DefaultSite/TagController.php, resources/views/defaultsite/mobile-v2/components/sections.blade.php, resources/views/defaultsite/mobile-v2/layouts/main-maverick.blade.php, resources/views/defaultsite/mobile-v2/layouts/main.blade.php
limit 25 data, fix var env, getNews
=> fix status code getNews

resources/views/defaultsite/mobile-v2/pages/detail/components/content/detail-topics.blade.php, resources/views/defaultsite/mobile-v2/pages/detail/components/textPhotocase/temp2.blade.php, resources/views/defaultsite/mobile-v2/pages/detail/components/textPhotocase/temp3.blade.php, resources/views/defaultsite/mobile-v2/pages/detail/index.blade.php
fix route detail content & add svg blade temp3 & temp4
=> fix detail content

public/static/mix-manifest.json, resources/assets/defaultsite/mobile-v2/css/detail-maverick.css, resources/views/defaultsite/mobile-v2/pages/detail/components/satu.blade.php
add logo trstdly on detail maverick
=> add logo image on headline screen detail maverick
